In [ ]:
Understanding Numpy: 
    without this u cannot exceute any library
    base layer is numpy

In [ ]:
what are the 3rd party libraries u have used in your project - interview qs

In [ ]:
how to install numpy:

In [3]:
!pip install numpy

In [5]:
!pip install numpy --upgrade

Requirement already up-to-date: numpy in c:\users\hema srinivas\anaconda3\lib\site-packages (1.18.1)


In [6]:
import numpy as np  #alias name is np -- np is industry used word, you can use any word here

In [7]:
array_one = np.array([1,2,3,4,5])

array_one

array([1, 2, 3, 4, 5])

In [8]:
type(array_one)

numpy.ndarray

In [ ]:
what is the difference between list and an array? What do you prefer using? -- interview qs
array is the most preferred used one
list and array - same features
specification wise- internalworking structure of an Array
    : vectors for processing the code ----> faster execution
    : better implementation of indexing ---> faster retrival of objects


In [9]:
numbers = [5,6,7,8,9,10]

array_two = np.array(numbers)

array_two

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
money_spent_dollars = [5,6,7,8,9,10]

In [ ]:
create an array of zeros with desired shape(x,y)


In [ ]:
x will ne no of rows
y will be no of columns

In [13]:
array_of_zeros = np.zeros((3,4))

array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
the dots -- internally implementation numpy uses float

In [ ]:
array uses float data type as default