In [6]:
array_of_ones = np.ones((3,4))

array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
import numpy as np

In [7]:
array_of_ones = np.ones((3,4))

array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
array_of_ones_int =np.ones((3,4),dtype=np.int16)  #the decimals gets disappeared -->typecasting -->int16  -->16 bytes

print(array_of_ones_int)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [9]:
array_empty = np.empty((2,3))  #empty array being created
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
identity matrix  #  interview qs with respect to numpy

In [10]:
array_eye=np.eye(3)  # see the ones in the output

array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#range functions ==> in numpy it is called arange

In [ ]:
#to print the array of even numbers

In [12]:
array_of_evens = np.arange(2,21,2)  #last number always exclusive -> syntax (startvalue,endvalue,stepcount)

array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])