In [2]:
import numpy as np

In [3]:
#printing of numpy arrays

In [4]:
a = np.arange(6)  #1D

In [5]:
print(a)

[0 1 2 3 4 5]


In [6]:
type(a)

numpy.ndarray

In [ ]:
2D Array

In [9]:
b = np.arange(12).reshape(4,3) #4*3 = 12
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [10]:
b = np.arange(12).reshape(5,2)

ValueError: cannot reshape array of size 12 into shape (5,2)

In [12]:
#3D_Array

In [15]:
c = np.arange(24).reshape(2,3,4) #2*3*4 = 24 --> 3D

print(c)  #print class  -->

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
# inroduction to statical concepts :


In [20]:
test_scores = np.array([32.32,56.98,21.52,44.32,55.63,13.75,43.47,43.34])

In [21]:
print('Mean test score are given below calculated :')

print(np.mean(test_scores))  # x = x/n

Mean test score are given below calculated :
38.91625


In [22]:
print('Median test score of the students')

print(np.median(test_scores))

Median test score of the students
43.405
