In [2]:
import numpy as np

In [ ]:
#basic operations in numpy:

In [3]:
a = np.array([10,10,10])

b = np.array([5,5,5])

In [4]:
a+b

array([15, 15, 15])

In [5]:
a-b

array([5, 5, 5])

In [6]:
b-a

array([-5, -5, -5])

In [7]:
a*b

array([50, 50, 50])

In [8]:
a/b # why r we receiving this 2. -- > point or decimal? --as float is the default

array([2., 2., 2.])

In [11]:
a%b  #modular operator ---> remiander as output

array([0, 0, 0], dtype=int32)

In [12]:
a%3 # modular operator gives us the remainder

array([1, 1, 1], dtype=int32)

In [ ]:
#comparison operator:

In [14]:
a<30  # 10<30

array([ True,  True,  True])

In [15]:
a>30  #10>30

array([False, False, False])

In [16]:
a**2  # squaring operators 10 square 

array([100, 100, 100], dtype=int32)

In [17]:
a**3

array([1000, 1000, 1000], dtype=int32)

In [ ]:
# dont want to create a nrew array

In [ ]:
req: want to modify an existing array with numpy

In [26]:
a = np.array([10,10,10])
a

array([10, 10, 10])

In [27]:
a+=3
a

array([13, 13, 13])

In [28]:
b += a
b

array([18, 18, 18])

In [ ]:
    unary operators --> 

In [29]:
ages = np.array([12,15,18,20])

In [31]:
ages.sum()

65

In [32]:
ages.min()

12

ages.max()

In [37]:
numbers = np.arange(12).reshape(3,4)
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
print(numbers) #print is diff then calling #encapsulation

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
